name: macOS

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macOS-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1

      - name: Tests
        run: |
          ./configure

