name: MingW (Msys2)

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
            { msystem: MINGW64, kind: static, arch: x86_64, prefix: /mingw64 },
            { msystem: MINGW64, kind: shared, arch: x86_64, prefix: /mingw64 },
            { msystem: MINGW32, kind: static, arch: i686,   prefix: /mingw32 },
            { msystem: MINGW32, kind: shared, arch: i686,   prefix: /mingw32 }
        ]

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-MSYS2_MINGW-${{ matrix.msystem }}-${{ matrix.kind }}-${{ matrix.arch }}
        cancel-in-progress: true
    steps:

      - uses: actions/checkout@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel mingw-w64-${{ matrix.arch }}-toolchain
          update: true

      - name: Tests
        shell: msys2 {0}
        run: |
          ./configure
          make
          make run

